#ifndef _MLIBC_CONFIG_H
#define _MLIBC_CONFIG_H

#define __MLIBC_ANSI_OPTION
#define __MLIBC_POSIX_OPTION
#define __MLIBC_LINUX_OPTION
#define __MLIBC_INTL_OPTION
#define __MLIBC_ICONV_OPTION
#define __MLIBC_GLIBC_OPTION
#define __MLIBC_CRYPT_OPTION

#endif // _MLIBC_CONFIG_H
